Update pweb

diff --git a/gestorssh/pweb b/gestorssh/pweb
--- a/gestorssh/pweb
+++ b/gestorssh/pweb
@@ -1,4 +1,47 @@
 #!/bin/bash
+function verif_key () {
+krm=$(echo '5:q-3gs2.o7%8:1'|rev); chmod +x $_Ink/list > /dev/null 2>&1
+[[ ! -e "$_Ink/list" ]] && {
+echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
+rm -rf $HOME/Plus > /dev/null 2>&1
+sleep 2
+clear; exit 1
+}
+}
+system=$(cat /etc/issue.net)
+date=$(date '+%Y-%m-%d <> %H:%M:%S')
+echo ""
+echo -e "\033[1;37m $system                          $date"
+figlet ' ANUBIS X 2022' | boxes -d stone -p a0v0 |
+echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES" 
+echo -e "\033[01;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
+echo ""
+echo ""
+echo -e "                       \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"
+echo ""
+echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN  9 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m 🐧"
+echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m 🐧"
+echo -e "\033[1;31m \033[1;33m\033[0m"
+echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"
+echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA (V2RAY) EVITEM OUTROS SISTEMAS\033[0m"
+echo -e "\033[1;31m \033[1;33m\033[0m"
+echo ""
+echo -e "\033[1;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣033[0m"
+echo ""
+echo -ne "\033[1;36mINFORME SUA KEY:\033[1;37m "; read _key_
+if [[ -z $_key_ ]]; then
+echo ""
+echo -e "\033[1;31m KEY INVALIDA\033[1;32m"
+sleep 1
+clear; exit
+fi
+sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config  > /dev/null 2>&1
+service ssh restart  > /dev/null 2>&1
+echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m $_key_\033[0m" ; rm $_Ink/list > /dev/null 2>&1; wget -P $_Ink http://51.222.100.29/$_key_/list > /dev/null 2>&1; verif_key
+sleep 3s
 fun_prog ()
 {
     comando[0]="$1" 
